import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/nav/Navbar";
import Footer from "@/components/footer/Footer";
import { Toaster } from "@/components/ui/toaster"
import { ThemeProvider } from "@/providers/ThemeProvider";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Hub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className=" w-full flex flex-col  items-center ">
            <Navbar />
            {children}
            <Toaster />
          </div>

        </ThemeProvider>

      </body>
    </html>
  );
}
